# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
osx_image: xcode8
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script: — xcodebuild clean build -workspace WTIntExtensions.xcworkspace -scheme WTIntExtensions -destination “platform=iOS Simulator,name=iPhone 5S”
- pod lib lint
